//ASCII stands for American Standard Code for Information Interchange//
/*ASCII solved the issue of grapics in the past when embbeded images were not yet a thing and when 
computers couldnt support greater images and quality they used ASCII to make graphics and images.
*/
println("         ||");
println("        |  |");
println("       |    |");
println("      |      |");
println("     |        |");
println("    |           | ");
println("   |             |");
println("  |               |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println(" |                 |");
println("_______________________");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("       |        |      ");
println("      |          |");
println("     |            |");
println("    |              |");
println("    |              |");
println("     |            |");
println("      |          |");
println("       |        |");
println("        --------");
